/**
 * What the /books forms showed before they moved to Frappe's meta, taken
 * from the old schema files: each form's `fieldname | label | placeholder |
 * section` layout in Frappe fieldnames, labels, table and quick edit
 * columns, list filters, colours, whether each link offered Create, and
 * quick view fields.
 * Tests check the Frappe-backed forms still show the same.
 */
export const previousForms = {
  layouts: {
    JournalEntry: [
      'name | Entry No |  | Default',
      'number_series | Number Series |  | Default',
      'entry_type | Entry Type | Entry Type | Default',
      'posting_date | Date |  | Default',
      'accounts | Account Entries |  | Accounts',
      'reference_number | Reference Number |  | References',
      'reference_date | Reference Date |  | References',
      'user_remark | User Remark | Add a remark | References',
      'attachment | Attachment | Add attachment | References',
    ],
    JournalEntryAccount: [
      'account | Account | Account | Default',
      'debit | Debit |  | Default',
      'credit | Credit |  | Default',
    ],
    AccountingLedgerEntry: [
      'name | Entry No. |  | Default',
      'posting_date | Date |  | Default',
      'party | Party |  | Default',
      'account | Account |  | Default',
      'debit | Debit |  | Details',
      'credit | Credit |  | Details',
      'voucher_type | Ref. Type |  | Reference',
      'voucher_no | Ref. Name |  | Reference',
      'reverted | Reverted |  | Reference',
      'reverts | Reverts |  | Reference',
    ],
    StockLedgerEntry: [
      'name | Entry No. |  | Default',
      'date | Date |  | Default',
      'location | Location |  | Details',
      'batch | Batch |  | Details',
      'serial_number | Serial Number |  | Details',
      'item | Item |  | Details',
      'rate | Rate |  | Details',
      'quantity | Quantity |  | Details',
      'reference_type | Ref. Type |  | Reference',
      'reference_name | Ref. Name |  | Reference',
    ],
    LoyaltyPointEntry: [
      'name | Entry No. |  | Default',
      'loyalty_program | Loyalty Program |  | Default',
      'loyalty_program_tier | Loyalty Program Tier |  | Default',
      'customer | Customer |  | Default',
      'invoice | Invoice |  | Default',
      'loyalty_points | Loyalty Points |  | Default',
      'purchase_amount | Purchase Amount |  | Default',
      'expiry_date | Expiry Date |  | Default',
      'posting_date | Posting Date |  | Default',
    ],
    Payment: [
      'number_series | Number Series |  | Default',
      'party | Party |  | Default',
      'date | Posting Date |  | Default',
      'payment_type | Payment Type | Payment Type | Default',
      'account | Party Account |  | Details',
      'payment_account | Payment Account |  | Details',
      'payment_method | Payment Method | Payment Method | Details',
      'clearance_date | Clearance Date | Clearance Date | Details',
      'reference_id | Ref. / Cheque No. | Ref. / Cheque No. | Details',
      'reference_date | Reference Date | Ref. Date | Details',
      'amount | Amount |  | Amounts',
      'writeoff | Write Off |  | Amounts',
      'amount_paid | Amount Paid |  | Amounts',
      'taxes | Taxes |  | Amounts',
      'payment_references | Payment Reference |  | References',
      'attachment | Attachment | Add attachment | References',
    ],
    PaymentFor: [
      'reference_type | Type | Type | Default',
      'reference_name | Name | Name | Default',
      'amount | Amount |  | Default',
    ],
    PrintSettings: [
      'logo | Logo |  | Default',
      'company_name | Company Name |  | Default',
      'email | Email | john@doe.com | Contacts',
      'phone | Phone | 9888900000 | Contacts',
      'address | Address |  | Contacts',
      'color | Color | Select Color | Customizations',
      'font | Font | Font | Customizations',
      'display_logo | Display Logo in Invoice |  | Customizations',
      'amount_in_words | Display Amount In Words |  | Customizations',
      'display_time | Display Time In Invoice |  | Customizations',
      'display_description | Display Description In Invoice |  | Customizations',
      'displaytermsandconditions | Display Terms and Conditions |  | Customizations',
      'terms_and_conditions | Terms and Conditions |  | Customizations',
    ],
  },
  labels: {
    JournalEntry: 'Journal Entry',
    JournalEntryAccount: 'Journal Entry Account',
    AccountingLedgerEntry: 'Accounting Ledger Entry',
    StockLedgerEntry: 'Stock Ledger Entry',
    LoyaltyPointEntry: 'Loyalty Point Entry',
    Payment: 'Payment',
    PaymentFor: 'Payment For',
    PrintSettings: 'Print Settings',
  },
  tableFields: {
    JournalEntryAccount: ['account', 'debit', 'credit'],
  },
  quickEditFields: {
    Payment: [
      'number_series',
      'party',
      'date',
      'payment_method',
      'account',
      'payment_type',
      'payment_account',
      'reference_id',
      'reference_date',
      'clearance_date',
      'amount',
      'writeoff',
      'amount_paid',
      'attachment',
      'payment_references',
    ],
  },
  listFilters: {
    JournalEntry: [
      'cancelled',
      'creation',
      'entry_type',
      'modified',
      'modified_by',
      'name',
      'number_series',
      'owner',
      'posting_date',
      'reference_date',
      'reference_number',
      'status',
      'submitted',
      'user_remark',
    ],
  },
  colors: {
    PrintSettings: [
      {
        label: 'Red',
        value: '#f56565',
      },
      {
        label: 'Orange',
        value: '#ed8936',
      },
      {
        label: 'Yellow',
        value: '#ecc94b',
      },
      {
        label: 'Green',
        value: '#48bb78',
      },
      {
        label: 'Teal',
        value: '#38b2ac',
      },
      {
        label: 'Blue',
        value: '#33a1ff',
      },
      {
        label: 'Indigo',
        value: '#667eea',
      },
      {
        label: 'Purple',
        value: '#9f7aea',
      },
      {
        label: 'Pink',
        value: '#ed64a6',
      },
      {
        label: 'Black',
        value: '#112B42',
      },
    ],
    // The POS button colour fields of Defaults and POS Profile.
    Buttons: [
      { label: 'Red', value: '#f98080' },
      { label: 'Orange', value: '#fbbf70' },
      { label: 'Yellow', value: '#fde047' },
      { label: 'Green', value: '#86efac' },
      { label: 'Teal', value: '#5eead4' },
      { label: 'Blue', value: '#60a5fa' },
      { label: 'Indigo', value: '#818cf8' },
      { label: 'Purple', value: '#a78bfa' },
      { label: 'Pink', value: '#f472b6' },
      { label: 'Black', value: '#9ca3af' },
    ],
  },
  stock: {
    StockMovement: {
      layout: [
        'number_series | Number Series |  | Default | ',
        'movement_type | Movement Type |  | Default | ',
        'date | Date |  | Default | ',
        'items | Items |  | Items | ',
        'amount | Total Amount |  | Items | ',
      ],
      quickEditFields: [
        'number_series',
        'date',
        'movement_type',
        'amount',
        'items',
      ],
    },
    Shipment: {
      layout: [
        'number_series | Number Series |  | Default | ',
        'party | Party |  | Default | ',
        'date | Date |  | Default | ',
        'items | Items |  | Items | ',
        'grand_total | Grand Total |  | Items | ',
        'terms | Notes | Add transfer terms | References | ',
        'attachment | Attachment | Add attachment | References | ',
        'back_reference | Back Reference |  | References | ',
        'return_against | Return Against |  | References | ',
      ],
      quickEditFields: [],
    },
    PurchaseReceipt: {
      layout: [
        'number_series | Number Series |  | Default | ',
        'party | Party |  | Default | ',
        'date | Date |  | Default | ',
        'items | Items |  | Items | ',
        'grand_total | Grand Total |  | Items | ',
        'terms | Notes | Add transfer terms | References | ',
        'attachment | Attachment | Add attachment | References | ',
        'back_reference | Back Reference |  | References | ',
        'return_against | Return Against |  | References | ',
      ],
      quickEditFields: [],
    },
    StockMovementItem: {
      layout: [
        'item | Item |  | Default | ',
        'from_location | From |  | Default | ',
        'to_location | To |  | Default | ',
        'transfer_unit | Transfer Unit | Unit | Default | ',
        'transfer_quantity | Qty. in Transfer Unit |  | Default | ',
        'unit | Stock Unit | Unit | Default | ',
        'batch | Batch |  | Default | ',
        'serial_number | Serial Number |  | Default | ',
        'quantity | Quantity |  | Default | ',
        'unit_conversion_factor | Conversion Factor |  | Default | ',
        'rate | Rate |  | Default | ',
        'amount | Amount |  | Default | ',
      ],
      tableFields: ['item', 'from_location', 'to_location', 'quantity', 'rate'],
      quickEditFields: [
        'item',
        'from_location',
        'to_location',
        'transfer_quantity',
        'transfer_unit',
        'batch',
        'serial_number',
        'quantity',
        'unit',
        'unit_conversion_factor',
        'rate',
        'amount',
      ],
    },
    ShipmentItem: {
      layout: [
        'item | Item |  | Default | ',
        'location | From Loc. |  | Default | ',
        'transfer_unit | Transfer Unit | Unit | Default | ',
        'transfer_quantity | Qty. in Transfer Unit |  | Default | ',
        'unit | Stock Unit | Unit | Default | ',
        'batch | Batch |  | Default | ',
        'serial_number | Serial Number |  | Default | ',
        'quantity | Quantity |  | Default | ',
        'unit_conversion_factor | Conversion Factor |  | Default | ',
        'rate | Rate |  | Default | ',
        'amount | Amount |  | Default | ',
        'item_discount_amount | Discount Amount |  | Default | ',
        'item_discount_percent | Discount Percent |  | Default | ',
        'description | Description | Item Description | Default | ',
        'hsn_code | HSN/SAC | HSN/SAC Code | Default | ',
      ],
      tableFields: ['item', 'location', 'quantity', 'rate', 'amount'],
      quickEditFields: [
        'item',
        'transfer_quantity',
        'transfer_unit',
        'batch',
        'serial_number',
        'quantity',
        'unit',
        'unit_conversion_factor',
        'description',
        'hsn_code',
        'location',
        'rate',
        'amount',
        'item_discount_amount',
        'item_discount_percent',
      ],
    },
    PurchaseReceiptItem: {
      layout: [
        'item | Item |  | Default | ',
        'location | To Loc. |  | Default | ',
        'transfer_unit | Transfer Unit | Unit | Default | ',
        'transfer_quantity | Qty. in Transfer Unit |  | Default | ',
        'unit | Stock Unit | Unit | Default | ',
        'batch | Batch |  | Default | ',
        'serial_number | Serial Number |  | Default | ',
        'quantity | Quantity |  | Default | ',
        'unit_conversion_factor | Conversion Factor |  | Default | ',
        'rate | Rate |  | Default | ',
        'amount | Amount |  | Default | ',
        'item_discount_amount | Discount Amount |  | Default | ',
        'item_discount_percent | Discount Percent |  | Default | ',
        'description | Description | Item Description | Default | ',
        'hsn_code | HSN/SAC | HSN/SAC Code | Default | ',
      ],
      tableFields: ['item', 'location', 'quantity', 'rate', 'amount'],
      quickEditFields: [
        'item',
        'transfer_quantity',
        'transfer_unit',
        'batch',
        'serial_number',
        'quantity',
        'unit',
        'unit_conversion_factor',
        'description',
        'hsn_code',
        'location',
        'rate',
        'amount',
        'item_discount_amount',
        'item_discount_percent',
      ],
    },
  },
  linkCreate: {
    'SetupWizard.country': false,
    'SetupWizard.currency': false,
    'Defaults.sales_payment_account': true,
    'Defaults.purchase_payment_account': true,
    'Defaults.shipment_location': true,
    'Defaults.purchase_receipt_location': true,
    'Defaults.sales_invoice_number_series': true,
    'Defaults.purchase_invoice_number_series': true,
    'Defaults.journal_entry_number_series': true,
    'Defaults.payment_number_series': true,
    'Defaults.stock_movement_number_series': true,
    'Defaults.shipment_number_series': true,
    'Defaults.purchase_receipt_number_series': true,
    'Defaults.sales_quote_number_series': true,
    'Defaults.sales_quote_print_template': false,
    'Defaults.sales_invoice_print_template': false,
    'Defaults.purchase_invoice_print_template': false,
    'Defaults.journal_entry_print_template': false,
    'Defaults.payment_print_template': false,
    'Defaults.shipment_print_template': false,
    'Defaults.purchase_receipt_print_template': false,
    'Defaults.stock_movement_print_template': false,
    'Defaults.pos_print_template': false,
    'Defaults.pos_customer': true,
    'PrintSettings.address': true,
    'Account.parent_books_account': false,
    'AccountingSettings.write_off_account': false,
    'AccountingSettings.round_off_account': false,
    'AccountingSettings.discount_account': false,
    'Party.address': true,
    'Party.default_account': true,
    'Party.currency': true,
    'Party.loyalty_program': true,
    'Lead.address': true,
    'Address.country': false,
    'ItemGroup.tax': true,
    'Item.item_group': true,
    'Item.unit': true,
    'Item.income_account': true,
    'Item.expense_account': true,
    'Item.tax': true,
    'LoyaltyProgram.expense_account': false,
    'Payment.number_series': true,
    'Payment.party': true,
    'Payment.account': true,
    'Payment.payment_account': true,
    'Payment.payment_method': true,
    'TaxSummary.account': false,
    'TaxSummary.from_account': false,
    'PaymentFor.reference_name': false,
    'PaymentMethod.account': false,
    'JournalEntry.number_series': true,
    'JournalEntryAccount.account': false,
    'CouponCode.pricing_rule': false,
    'PriceListItem.item': true,
    'PriceListItem.unit': false,
    'PricingRule.number_series': true,
    'PricingRule.free_item': false,
    'PricingRule.free_item_unit': false,
    'PricingRuleItem.item': false,
    'PricingRuleItem.unit': true,
    'TaxDetail.account': true,
    'TaxDetail.payment_account': true,
    'InventorySettings.default_location': true,
    'InventorySettings.stock_in_hand': false,
    'InventorySettings.stock_received_but_not_billed': false,
    'InventorySettings.cost_of_goods_sold': false,
    'Location.address': true,
    'StockMovement.number_series': true,
    'StockMovementItem.item': true,
    'StockMovementItem.from_location': true,
    'StockMovementItem.to_location': true,
    'StockMovementItem.transfer_unit': false,
    'StockMovementItem.batch': true,
    'Batch.item': true,
    'SerialNumber.item': true,
    'POSSettings.inventory': true,
    'POSSettings.pos_profile': true,
    'POSSettings.cash_account': true,
    'POSSettings.write_off_account': true,
    'POSSettings.default_account': true,
    'POSProfile.pos_customer': true,
    'POSProfile.inventory': true,
    'POSProfile.pos_print_template': false,
    'POSClosingShift.opening_shift': false,
    'SalesInvoice.number_series': true,
    'SalesInvoice.party': true,
    'SalesInvoice.account': true,
    'SalesInvoice.price_list': false,
    'SalesInvoice.back_reference': false,
    'SalesInvoice.return_against': false,
    'SalesInvoice.quote': false,
    'SalesInvoiceItem.item': true,
    'SalesInvoiceItem.transfer_unit': false,
    'SalesInvoiceItem.batch': true,
    'SalesInvoiceItem.account': false,
    'SalesInvoiceItem.tax': true,
    'AppliedCouponCodes.coupons': false,
    'PurchaseInvoice.number_series': true,
    'PurchaseInvoice.party': true,
    'PurchaseInvoice.account': true,
    'PurchaseInvoice.price_list': false,
    'PurchaseInvoice.back_reference': false,
    'PurchaseInvoice.return_against': false,
    'PurchaseInvoiceItem.item': true,
    'PurchaseInvoiceItem.transfer_unit': false,
    'PurchaseInvoiceItem.batch': true,
    'PurchaseInvoiceItem.account': false,
    'PurchaseInvoiceItem.tax': true,
    'SalesQuote.number_series': true,
    'SalesQuote.party': true,
    'SalesQuote.price_list': false,
    'SalesQuoteItem.item': true,
    'SalesQuoteItem.transfer_unit': false,
    'SalesQuoteItem.batch': true,
    'SalesQuoteItem.account': false,
    'SalesQuoteItem.tax': true,
    'Shipment.number_series': true,
    'Shipment.party': true,
    'Shipment.back_reference': false,
    'Shipment.return_against': false,
    'ShipmentItem.item': false,
    'ShipmentItem.location': true,
    'ShipmentItem.transfer_unit': false,
    'ShipmentItem.batch': false,
    'PurchaseReceipt.number_series': true,
    'PurchaseReceipt.party': true,
    'PurchaseReceipt.back_reference': false,
    'PurchaseReceipt.return_against': false,
    'PurchaseReceiptItem.item': false,
    'PurchaseReceiptItem.location': true,
    'PurchaseReceiptItem.transfer_unit': false,
    'PurchaseReceiptItem.batch': false,
  },
  // What quick views listed, as `fieldname | label`, where the form shows others.
  quickViews: {
    Payment: [
      'number_series | Number Series',
      'party | Party',
      'date | Posting Date',
      'payment_type | Payment Type',
      'account | Party Account',
      'payment_account | Payment Account',
      'payment_method | Payment Method',
      'clearance_date | Clearance Date',
      'reference_id | Ref. / Cheque No.',
      'reference_date | Reference Date',
      'amount | Amount',
      'writeoff | Write Off',
    ],
    POSOpeningShift: ['opening_date | Opening Date'],
    POSClosingShift: [
      'closing_date | Closing Date',
      'opening_shift | Opening Shift',
    ],
    SalesInvoice: [
      'number_series | Number Series',
      'party | Customer',
      'account | Account',
      'date | Date',
      'price_list | Price List',
      'net_total | Net Total',
      'total_discount | Discount',
      'loyalty_points_amount | Loyalty Points Redeemed',
      'base_grand_total | Base Grand Total',
      'grand_total | Grand Total',
      'discount_after_tax | Apply Discount After Tax',
      'make_auto_payment | Make Payment On Submit',
      'make_auto_stock_transfer | Make Shipment On Submit',
      'outstanding_amount | Outstanding Amount',
      'stock_not_transferred | Stock Not Shipped',
      'terms | Notes',
      'back_reference | Back Reference',
      'return_against | Return Against',
      'quote | Quote Reference',
      'loyalty_program | Loyalty Program',
      'available_loyalty_points | Available Loyalty Points',
      'redeem_loyalty_points | Redeem Loyalty Points',
      'loyalty_points | Loyalty Points',
    ],
    PurchaseInvoice: [
      'number_series | Number Series',
      'party | Supplier',
      'account | Account',
      'date | Date',
      'price_list | Price List',
      'net_total | Net Total',
      'total_discount | Discount',
      'base_grand_total | Base Grand Total',
      'grand_total | Grand Total',
      'discount_after_tax | Apply Discount After Tax',
      'make_auto_payment | Make Payment On Submit',
      'make_auto_stock_transfer | Make Purchase Receipt On Submit',
      'outstanding_amount | Outstanding Amount',
      'stock_not_transferred | Stock Not Received',
      'terms | Notes',
      'back_reference | Back Reference',
      'return_against | Return Against',
    ],
    SalesQuote: [
      'number_series | Number Series',
      'party | Customer',
      'date | Date',
      'price_list | Price List',
      'net_total | Net Total',
      'total_discount | Discount',
      'base_grand_total | Base Grand Total',
      'grand_total | Grand Total',
      'discount_after_tax | Apply Discount After Tax',
      'outstanding_amount | Outstanding Amount',
      'terms | Notes',
      'reference_type | Type',
    ],
  },
};
