dbfilename redis_queue.rdb
dir /workspaces/Desk/books-bench/config/pids
pidfile /workspaces/Desk/books-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /workspaces/Desk/books-bench/config/redis_queue.acl
